spring.application.name=demo

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb+srv://danil12314:${DB_PASSWORD}@cluster0.2drv2.mongodb.net/mydatabase?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.authentication-database=admin

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.endpoint.env.show-values=when_authorized
management.endpoint.env.keys-to-sanitize= password
spring.mail.host=smtp.example.com
spring.mail.username=myemail@test.com
spring.mail.password=password2314

